services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    networks:
      - ry_net
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/certbot/conf:/etc/letsencrypt
    entrypoint: /bin/sh
    command: >
      -c "while true; do
           certbot renew --webroot -w /var/www/certbot --deploy-hook 'nginx -s reload';
           sleep 12h;
         done"
    networks:
      - ry_net
    restart: unless-stopped

  backend:
    image: sumnic82/ry-backend:${IMAGE_TAG}
    env_file:
      - ./apps/backend/.env
    volumes:
      - ./backend/apps/static:/app/static
    networks:
      - ry_net

  postgres:
    image: postgres:16
    env_file:
      - ./apps/backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ry_net

  # migrate:
  #   image: sumnic82/rodnaya-server:${IMAGE_TAG}
  #   command: yarn migrate:prod
  #   depends_on:
  #     - postgres


networks:
  ry_net:
volumes:
  pgdata:
